### ISSUE TITLE
webbrowser.Error: could not locate runnable browser on ubuntu 16.04

### ISSUE THREAD

**Issue by bicepjai** [biancasubion/jupyshare#5]
Issue with line 195 code on jupyshare/jupyshare/share.py , it should probably have try catch.

`webbrowser.get(args.browser).open_new_tab(notebook_url)
`

It throws the following error
```
(deepl) haha (master)[jupyshare]$ jupyshare release
Grabbing open notebooks...

Which notebook are you referring to?
     | 8888 | /home/haha/Projects/myclasses
NOTEBOOK PORT: 8888
Opening notebook on port 8888 up...
Opened! To see a list of open notebooks try running jupyshare show
Your notebook is found on https://ffdgdgb.ngrok.io/?token=3164d011a67a2
Traceback (most recent call last):
  File "/home/haha/Programs/anaconda2/envs/deepl/bin/jupyshare", line 11, in <module>
    sys.exit(main())
  File "/home/haha/Programs/anaconda2/envs/deepl/lib/python2.7/site-packages/jupyshare/share.py", line 205, in main
    release(jshare_db, args)
  File "/home/haha/Programs/anaconda2/envs/deepl/lib/python2.7/site-packages/jupyshare/share.py", line 195, in release
    webbrowser.get(args.browser).open_new_tab(notebook_url)
  File "/home/haha/Programs/anaconda2/envs/deepl/lib/python2.7/webbrowser.py", line 52, in get
    raise Error("could not locate runnable browser")
webbrowser.Error: could not locate runnable browser

```

**Comment by beacoding** [comment]
Thanks for this! Will fix it.
