### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by xiaoxinyi** [biancasubion/jupyshare#6]
```
$ jupyshare release
Grabbing open notebooks...
Traceback (most recent call last):
  File "~i/anaconda2/bin/jupyshare", line 11, in <module>
    sys.exit(main())
  File "~/anaconda2/lib/python2.7/site-packages/jupyshare/share.py", line 205, in main
    release(jshare_db, args)
  File "~/anaconda2/lib/python2.7/site-packages/jupyshare/share.py", line 146, in release
    raw_notebooks = get_notebooks(jshare_db)
  File "~/anaconda2/lib/python2.7/site-packages/jupyshare/share.py", line 35, in get_notebooks
    port, token = re.sub(r'[?|$|.|!/\/]',r'',port_token[0]), port_token[1].strip()
IndexError: list index out of range
```

**Comment by beacoding** [comment]
hey can you show me what happens when you type in `jupyter notebook list`?

**Comment by mxmeier** [comment]
This looks like the same error that I got earlier (Issue #4 ). Try to update your jupyter.

**Comment by beacoding** [comment]
Closing. Thanks @mxmeier!
